version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    container_name: HTTPServer


    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - custom_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usersdb
    ports:
      - "5002:5002"
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - custom_network
  
  microservice:
    build:
      context: .
      dockerfile: Dockerfile.microservice
    networks:
      - custom_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - server
      - microservice
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
