name: CI
run-name: ${{ github.actor }} run CI
env:
  CC: clang
  CXX: clang++
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++ clang make cmake cppcheck libcurl4-openssl-dev

      #- run: git submodule update --init --recursive
      - run: mkdir -p build && cd build && cmake .. && make

      - run: cd ..
      - name: Client-sided tests
        run: |
          cd build
          ./ClientTest
          cd ..
      - name: Server-sided tests
        run: |
          cd build
          ./ServerTest
          cd ..
      - name: Static tests (only WARNINGS)
        run: cppcheck --enable=warning --std=c++17 --force .


